### ISSUE TITLE
Set up the profile back-end

### ISSUE THREAD

**Issue by RomanHyde** [Frictionless-Faction/FricFracChat#29]
I'm going to be setting up the back-end for the profiles. I'm going to need someone on the front end to implement this (on the front end).

- [x] uid (from user object)
- [x] bio
- [x] status

**Comment by RomanHyde** [comment]
**branch:** 
`feature/29`

**Tasks:**
- [x] reinitialise for the test server
- [x] change .env

**Switching Back:**
- [ ] reinitialise for the main server
- [ ] change .env back

**Comment by RomanHyde** [comment]
Check out the following issues for continued changes on branch `feature/29`

[Site mapping #17 ](https://github.com/Frictionless-Faction/FricFracChat/issues/17)
[Set up auth context #39](https://github.com/Frictionless-Faction/FricFracChat/issues/39)
